# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: agriyakhetarpal@outlook.com
author_name: Agriya Khetarpal
has_ai_rules: false
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlite-pandoc-pdf-exporter
project_short_description: A PDF exporter for JupyterLite based on a WebAssembly distribution
    of Pandoc
python_name: jupyterlite_pandoc_pdf_exporter
repository: https://github.com/agriyakhetarpal/jupyterlite-pandoc-pdf-exporter
test: true
